<?php

function getDemoProducts(): array
{
    return [
        1 => [
            'title' => 'Unique & Charming Holiday Home by Borrevannet',
            'price' => 3000000,
            'price_display' => '3,000,000 kr',
            'total_price' => '3,076,090 kr',
            'location' => 'Nykirke',
            'category' => 'Property Rentals',
            'badge' => '🏷️ Recommended',
            'img' => 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=800&auto=format&fit=crop&q=80',
            'desc' => 'A stunning holiday home nestled by the shores of Borrevannet. Enjoy the peaceful surroundings, a private dock, and beautiful sunsets. Perfect for families or as a weekend getaway. The property includes a fully equipped kitchen, 3 bedrooms, and a large terrace overlooking the lake.',
            'specs' => ['Bedrooms' => '3', 'Bathrooms' => '2', 'Size' => '120 m²', 'Year Built' => '2005', 'Condition' => 'Excellent', 'Type' => 'Holiday Home'],
            'owner' => ['name' => 'Jean Pierre K.', 'since' => 'Member since 2021', 'ads' => '4 active ads', 'rating' => '4.8', 'email' => 'jean.pierre@demo.rondera.com'],
            'subtitle' => 'Total price: 3,076,090 kr',
            'extra' => '✔️ Ready to Ship',
        ],
        2 => [
            'title' => 'Large and Beautiful Smallholding of approx. 11.6 Acres',
            'price' => 10490000,
            'price_display' => '10,490,000 kr',
            'total_price' => '10,753,340 kr',
            'location' => 'Spongdal',
            'category' => 'Property Sales',
            'badge' => '🏷️ Featured',
            'img' => 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&auto=format&fit=crop&q=80',
            'desc' => 'A rare opportunity to acquire a large, beautiful smallholding spanning 11.6 acres. Includes a main farmhouse, two outbuildings, fertile land, and a private stream. Ideal for farming, agro-tourism, or as a private retreat.',
            'specs' => ['Land Area' => '11.6 acres', 'Buildings' => '3', 'Water Supply' => 'Private stream', 'Year Built' => '1980', 'Condition' => 'Good', 'Type' => 'Smallholding'],
            'owner' => ['name' => 'Marie Noel', 'since' => 'Member since 2019', 'ads' => '7 active ads', 'rating' => '4.9', 'email' => 'marie.noel@demo.rondera.com'],
            'subtitle' => 'Total price: 10,753,340 kr',
            'extra' => '✔️ Ready to Ship',
        ],
        3 => [
            'title' => 'Toyota RAV4 Plug-In Hybrid — Low Mileage',
            'price' => 359900,
            'price_display' => '359,900 kr',
            'total_price' => '359,900 kr',
            'location' => 'Oslo',
            'category' => 'Vehicles for Sale',
            'badge' => '',
            'img' => 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800&auto=format&fit=crop&q=80',
            'desc' => 'Well-maintained Toyota RAV4 Plug-In Hybrid. Very low mileage for its year with full service history. Comes with winter wheels, tow bar, panoramic roof, and heated front seats. Non-smoker vehicle, always garaged.',
            'specs' => ['Year' => '2021', 'Mileage' => '45,000 km', 'Fuel' => 'Plug-In Hybrid', 'Gearbox' => 'Automatic', 'Color' => 'Lunar Rock', 'Seats' => '5'],
            'owner' => ['name' => 'Alexis B.', 'since' => 'Member since 2020', 'ads' => '2 active ads', 'rating' => '4.7', 'email' => 'alexis.b@demo.rondera.com'],
            'subtitle' => 'Year: 2021 | 45,000 km',
            'extra' => '✔️ Ready to Ship',
        ],
        4 => [
            'title' => 'Charming 3-Story Detached House with Garden',
            'price' => 19000000,
            'price_display' => '19,000,000 kr',
            'total_price' => '19,000,000 kr',
            'location' => 'Oslo / Skjetten',
            'category' => 'Property Sales',
            'badge' => '🏷️ Hot Offer',
            'img' => 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
            'desc' => 'Beautiful 3-story detached house in a quiet residential area. Features a large garden, a double garage, and a modern open-plan kitchen. Walking distance to schools and public transport.',
            'specs' => ['Bedrooms' => '5', 'Bathrooms' => '3', 'Size' => '210 m²', 'Year Built' => '2002', 'Garage' => 'Double', 'Type' => 'Detached House'],
            'owner' => ['name' => 'Claudette M.', 'since' => 'Member since 2018', 'ads' => '1 active ad', 'rating' => '5.0', 'email' => 'claudette.m@demo.rondera.com'],
            'subtitle' => '5 bedrooms | 210 m²',
            'extra' => '✔️ Ready to Ship',
        ],
        5 => [
            'title' => 'Cinderella Ecocat Incineration Toilet — Like New',
            'price' => 5500,
            'price_display' => '5,500 kr',
            'total_price' => '5,500 kr',
            'location' => 'Tranby',
            'category' => 'Marketplace',
            'badge' => '',
            'img' => 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&auto=format&fit=crop&q=80',
            'desc' => 'Barely used Cinderella Ecocat incineration toilet. Fully cleaned, serviced, and ready for use. Perfect for cabins, boats, or any off-grid setup. Original box and manual included.',
            'specs' => ['Brand' => 'Cinderella', 'Model' => 'Ecocat', 'Condition' => 'Like New', 'Fuel' => 'Electric', 'Capacity' => '3–4 persons'],
            'owner' => ['name' => 'Bernard T.', 'since' => 'Member since 2022', 'ads' => '3 active ads', 'rating' => '4.6', 'email' => 'bernard.t@demo.rondera.com'],
            'subtitle' => 'Cleaned and fully serviced',
            'extra' => '✔️ Ready to Ship',
        ],
        6 => [
            'title' => 'MacBook Air M2 — Space Gray, 256GB SSD',
            'price' => 5990,
            'price_display' => '5,990 kr',
            'total_price' => '5,990 kr',
            'location' => 'Bergen',
            'category' => 'Electronics',
            'badge' => '🏷️ Popular',
            'img' => 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
            'desc' => 'Selling my MacBook Air M2 in Space Gray. In excellent condition with a battery health of 98%. Comes with original charger and box. No scratches or dents. Reason for selling: upgraded to a Pro.',
            'specs' => ['Chip' => 'Apple M2', 'RAM' => '8GB', 'Storage' => '256GB SSD', 'Screen' => '13.6"', 'Battery' => '98%', 'OS' => 'macOS Sonoma'],
            'owner' => ['name' => 'Sophie L.', 'since' => 'Member since 2023', 'ads' => '5 active ads', 'rating' => '4.9', 'email' => 'sophie.l@demo.rondera.com'],
            'subtitle' => 'Battery health: 98%',
            'extra' => '✔️ Ready to Ship',
        ],
        7 => [
            'title' => 'Sunlight T68 Motorhome — Perfect Family Camper',
            'price' => 599000,
            'price_display' => '599,000 kr',
            'total_price' => '599,000 kr',
            'location' => 'Jessheim',
            'category' => 'Vehicles for Sale',
            'badge' => '🏷️ Weekly Deal',
            'img' => 'https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?w=800&auto=format&fit=crop&q=80',
            'desc' => 'Sunlight T68 fully-equipped motorhome in great condition. Includes solar panels, awning, GPS, reverse camera, and a full kitchen. Perfect for long family road trips across Europe. Serviced annually.',
            'specs' => ['Year' => '2019', 'Mileage' => '68,000 km', 'Berths' => '4', 'Length' => '6.9m', 'Solar' => 'Yes', 'Fuel' => 'Diesel'],
            'owner' => ['name' => 'Patrick H.', 'since' => 'Member since 2017', 'ads' => '2 active ads', 'rating' => '4.8', 'email' => 'patrick.h@demo.rondera.com'],
            'subtitle' => 'Year: 2019 | Fully equipped',
            'extra' => '✔️ Ready to Ship',
        ],
        8 => [
            'title' => 'Honda CB 350 F Vintage Motorcycle',
            'price' => 47000,
            'price_display' => '47,000 kr',
            'total_price' => '47,000 kr',
            'location' => 'Kvelde',
            'category' => 'Vehicles for Sale',
            'badge' => '',
            'img' => 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=800&auto=format&fit=crop&q=80',
            'desc' => 'Classic Honda CB 350 F in excellent condition for its age. Recently restored with new carburetors, chain, and a fresh paint job. A true collector\'s piece that still runs beautifully.',
            'specs' => ['Year' => '1973', 'Engine' => '350cc', 'Color' => 'Candy Red', 'Condition' => 'Excellent', 'Km' => '28,000 km', 'Type' => 'Classic'],
            'owner' => ['name' => 'Erik V.', 'since' => 'Member since 2016', 'ads' => '6 active ads', 'rating' => '4.7', 'email' => 'erik.v@demo.rondera.com'],
            'subtitle' => 'Year: 1973 | Excellent condition',
            'extra' => '✔️ Ready to Ship',
        ],
    ];
}
